onlyBuiltDependencies:
  - '@intlify/vue-i18n-bridge'
  - '@intlify/vue-router-bridge'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi

overrides:
  sharp: $sharp

shellEmulator: true

strictDepBuilds: true
