ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@intlify/vue-i18n-bridge'
  - '@intlify/vue-router-bridge'
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
