allowBuilds:
  '@intlify/vue-i18n-bridge': true
  '@intlify/vue-router-bridge': true
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: true

overrides:
  sharp: $sharp

shellEmulator: true

strictDepBuilds: true
